services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:alpine'
    networks:
      - eth-proxy
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
  api:
    container_name: api
    build: ./api
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - eth-proxy
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - path: ./api/.env
        required: true
  proxy:
    container_name: proxy
    build: ./proxy
    restart: unless-stopped
    networks:
      - eth-proxy
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - path: ./proxy/.env
        required: true

networks:
  eth-proxy:
    driver: bridge