{
 "title": "Ethereum API",
 "description": "A new GIN Http API Overview",
 "tags": [ "API" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "label_values(service_http_request_count_total{endpoint!~\"/metrics\", status!=\"404\", job=~\"$job_value\"}, endpoint)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(service_http_request_count_total, method)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(service_http_request_count_total, status)"
   },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" },
   { "name": "job_value", "query": "api" }
  ]
 },
 "panels": [
  {
   "title": "Service last updated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - service_uptime{job=~\"$job_value\"}) * 1000"
    }
   ]
  },
  {
   "title": "Requests QPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_request_count_total{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_uptime{job=~\"$job_value\"}"
    }
   ]
  },
  {
   "title": "Request size(bytes) per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_request_size_bytes_sum{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])\n/\nrate(service_http_request_size_bytes_count{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_request_duration_seconds_sum{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])\r\n/\r\nrate(service_http_request_duration_seconds_count{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(service_http_request_duration_seconds_bucket{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Response size(bytes) per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_response_size_bytes_sum{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])\n/\nrate(service_http_response_size_bytes_count{job=~\"$job_value\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__rate_interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  }
 ]
}